format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$directory\
$kubernetes\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character"""
command_timeout = 1000
[c]
disabled = true
[kubernetes]
disabled = false
format = 'on [☸ $context](dimmed yellow) '
[kubernetes.context_aliases]
'.*prod.*' = 'prod'
'.*stage.*' = 'stage'
'.*management.*' = 'management'
'.*playground.*' = 'playground'
[aws]
format = 'on [$symbol$region]($style) '
style = 'bold blue'
symbol = '🅰  '
[aws.region_aliases]
eu-central-1 = 'eu-c-1'
